//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.29 at 09:40:02 PM CDT 
//


package mx.gob.sat.v33.adapter;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class DateAdapter
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (mx.gob.sat.v33.binding.DateTimeCustomBinder.parseDateTime(value));
    }

    public String marshal(Date value) {
    	if (value != null) {
    		return (mx.gob.sat.v33.binding.DateTimeCustomBinder.printDateTime(value));
    	} else {
    		return null;
    	}
    }

}
